"""Add supplier relationship to Product model with named constraint

Revision ID: f46226ace61b
Revises: 
Create Date: 2025-05-13 00:13:49.749885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46226ace61b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_supplier', 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_supplier', type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
